# Use the official Node.js 20 image.
# https://hub.docker.com/_/node
FROM node:20

# Expose the port the app runs on
EXPOSE 3000

# Run the web service on container startup.
CMD [ "node", "server.js" ]
