import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Script from "next/script";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <main className="flex min-h-screen flex-col items-center justify-between p-24">
          {children}
          <Script
            id="loadCustomTrackingScript"
            async
            strategy="beforeInteractive"
            src="http://localhost:3000/script.js"
          />
          <Script id="SetAutoTrackingPageView" strategy="beforeInteractive">
            {`window.CustomDataLayer.config({ send_page_view: true })`}
          </Script>
        </main>
      </body>
    </html>
  );
}
